### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by peteryao7** [peteryao7/off-by-one#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

I think the biggest issue at the moment is rendering errors in the /signup and /login pages. If you try signing up or logging in with invalid credentials on SO, red boxes pop up next to the text field that display the relevant error. I'm not totally sure if this is necessary to implement, but if so, I'd like some advice on how to approach it!

**Comment by eshoule** [comment]
Looks good - a couple more things to fix, and then you're good to go.

- [ ] make sure the footer is always at the bottom of the page (it looks a little strange floating in the middle)
- [ ] errors don't display on the splash page if I try to sign up with an existing user.

**Comment by eshoule** [comment]
I'm going to close this issue, but you need to style your errors on the sign up splash page.
